#!/bin/csh
set P=$1
caget ${P}SR_aoDISP.DISP
caget ${P}SR_ao.PREC
caget ${P}SR_bo.IVOV
caget ${P}SR_ao.SCAN
caget ${P}SR_ao.VAL
caget ${P}SR_scaler.RATE
caget ${P}SR_ao.DESC
caget ${P}SR_ao.OUT
caget ${P}SR_longout
caget ${P}SR_bi.SVAL
caget ${P}SR_char_array
caget ${P}SR_double_array
caget ${P}SR_float_array
caget ${P}SR_long_array
caget ${P}SR_short_array
caget ${P}SR_string_array
caget ${P}SR_uchar_array
caget ${P}SR_ulong_array
caget ${P}SR_ushort_array
